export const theme = {
  color_key: '#FEAC3E',
  color_textKey: '#595959',
  color_textBlack: '#333333',
  color_textWhite: '#FFFFFF',
  color_textRed: '#D80000',
  color_textGray: '#909090',
  color_textPink: '#FF6161',
  color_textLightOrange: '#FBE2BF',
  color_textOrange: '#FF9B14',
  color_bgWhite: '#FFFFFF',
  color_bgLightGray: '#F5F5F5',
  color_bgLightPink: '#FEDADA',
  color_bgLightOrange: '#FBE2BF',
  color_borderGray: '#B4B4B4',

  fontSize_xxs: '12px',
  fontSize_xs: '14px',
  fontSize_sm: '16px',
  fontSize_reg: '18px',
  fontSize_md: '20px',
  fontSize_lg: '22px',
  fontSize_xl: '24px',
} as const;
